### PR TITLE
REL: 0.2.1

### PR DESCRIPTION
**Pull request by parente**

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Any thoughts on making this `noarch: python`?

**Comment by ericdill** [comment]
> Any thoughts on making this noarch: python?

:+1: in theory, but :man_shrugging: in practice because then me and/or @parente will need to fix constructor. 

Or, actually, we'll just re-package kernda internally since that's far less work than getting a PR merged into constructor that would properly deal with noarch :)

Up to @parente imo

**Comment by mariusvniekerk** [comment]
yeah and i'd also love to use this in a constructor

**Comment by parente** [comment]
> yeah and i'd also love to use this in a constructor

My vote is to leave it as arch for the time being, given that @mariusvniekerk requested this release to get easier access to his kernda fixes.

**Comment by jakirkham** [comment]
Well I’m raising this as Travis CI’s macOS queue has gotten pretty messed up and has been so for a while.

Did you see [this comment]( https://github.com/conda/constructor/issues/86#issuecomment-358895352 )? Expect a similar strategy will work just as well on macOS and Linux.

**Comment by mariusvniekerk** [comment]
@parente please merge

**Comment by parente** [comment]
@mariusvniekerk  done.

@jakirkham Thanks for the pointer to the post-build trick. I'll have to give it a shot and see if it catches entrypoint scripts generated by setuptools too.

**Pull request merged**
